### PR TITLE
Updated for indentation of code

### PR DESCRIPTION
**Pull request by gnmmarechal**

### CODE REVIEW

**Comment by filfat** [comment]
That's a lot better, it's still not pretty but at least it's readable

**Comment by gnmmarechal** [comment]
Indeed. non-indented code is a pain to read. I just noticed I misspelled indentation x.x

**Comment by Pirater12** [comment]
Although I can tell you advanced The code will once again become dirty with time

**Comment by gnmmarechal** [comment]
Huh, Pirater, indenting is not hard x.x and it makes it more readable. Is there any reason why you won't indent the code?

**Comment by Pirater12** [comment]
Maybe you are right(i will try to keep my code indent) but I am a very hasty type of person I just add a few lines of code,test it and then upload it on github. :p

**Comment by Pirater12** [comment]
Maybe you are right(i will try to keep my code indent) but I am a very hasty type of person I just add a few lines of code,test it and then upload it on github. :p

**Comment by gnmmarechal** [comment]
Uh, you can use this to auto-indent your code:
http://format.krzaq.cc/

**Pull request merged**
