### PR TITLE
Redesigned banner, icon

### PR DESCRIPTION
**Pull request by NinjaBoyLao**

### CODE REVIEW

**Comment by gnmmarechal** [comment]
Frankly. I prefer a round-corner design for the upper banner. No?

**Comment by Pirater12** [comment]
I think this one is better..

**Comment by gnmmarechal** [comment]
I can do that myself, I'll submit a PR later.

**Comment by NinjaBoyLao** [comment]
I can do this, yes

**Comment by NinjaBoyLao** [comment]
It's been done cleanly, awaiting approval

**Pull request merged**
